language: English
code: en
start: 
  message: |
    Hi!
    You can use this bot to generate video summaries.

    🌐 Paste a link to an youtube video
    ▶️ Or upload a video file
    It will take a while

    Type `\help` for more info
  description: Start bot

cancel:
  message: ✅ Canceled
  description: Cancel the current task

help:
  message: |
    🌐 Paste a link to youtube video to process it
    ▶️ Or upload a video file

    If you don't want to process it, you can `\cancel` the current operation

    Access settings using this commands
    `\change_language` - Change bot's language
    `\document_format` - Change output document format
    `\document_language` - Translate document to this language using current LLM
    `\text_format` - Specify how your summary should be structured. It affects processing speed
  description: Displays help message

change_language: 
  message: |
    change bots language to
  description: Change bot's interface language
  button1: "English"
  button2: "русский"

document_format:
  message: |
    Change document output format to
  description: Change output document format
  button1: "markdown"
  # button2: "pdf"

document_language:
  message: |
    Receive answer in
  description: Change document's language
  button1: "auto"
  button2: "English"
  button3: "русский"

text_format:
  message: |
    Text structure isd
  description: Defines text structure
  button1: Full
  value1: full
  button2: Dry
  value2: dry
  button3: Regular
  value3: facts

general:
  success: Success!
  got_link: 🌐 Processing youtube video
  got_video: ▶️ Processing video
  transcribing: Transcribing video, please wait
  processing: Processing text, please wait
  document_caption: Here is your summary!
  startup: Bot started
  shutdown: Bot shutdown

errors:
  critical: Some error has happened. Unable to process request
  nothing_to_cancel: ✖️ Nothing to cancel
  bad_link: ✖️ Bad link. Unable to process
  config_access: Config file access error
  composer: Error in document generation
  llm: Error in text generation module
  audio_model: Error in transcription process
  too_many_tasks: ⛔ Too many tasks. Please try again later.
  file_not_found: Could not find file in the provided path
  unknown_setting: ⛔ You chose a wrong setting, please use keyboard
