language: русский
code: ru
start: 
  message: |
    Привет!
    Ты можешь использовать этого бота для создания выжимки из видео.

    🌐 Вставьте ссылку на видео с YouTube
    ▶️ Или загрузите видеофайл
    Это займет некоторое время

    Введите `\help` для получения дополнительной информации
  description: Запустить бота

cancel:
  message: ✅ Отменено
  description: Отменить текущую операцию

help:
  message: |
    🌐 Вставь ссылку на видео с YouTube, чтобы обработать его
    ▶️ Или загрузи видеофайл

    Для прерывания операции можно ввести `\cancel`

    Получите доступ к настройкам с помощью этих команд
    `\change_language` - Изменить язык бота
    `\document_format` - Изменить формат выходного документа
    `\document_language` - Перевести документ на этот язык с помощью текущего LLM
    `\text_format` - Определение структуры документа. Влияет на скорость обработки
  description: Показать помощь

change_language: 
  message: |
    Изменить язык на
  description: Изменить язык бота
  button1: "English"
  button2: "русский"

document_format:
  message: |
    Изменить язык в документе
  description: Изменить язык в документе
  button1: "markdown"
  # button2: "pdf"

document_language:
  message: |
    Изменить язык в документе
  description: Изменить язык в документе
  button1: "auto"
  button2: "English"
  button3: "русский"

text_format:
  message: |
    Какой шаблон использовать?
  description: Определение структуры документа
  button1: Полная
  value1: full
  button2: Краткая
  value2: dry
  button3: Обычная
  value3: facts

general:
  success: Готово!
  got_link: 🌐 Обработка видео с youtube
  got_video: ▶️ Обработка видео
  transcribing: Расшифровка видео, пожалуйста подождите
  processing: Обработка текста, пожалуйста подождите
  document_caption: Документ с содержанием видео
  startup: Bot started
  shutdown: Bot shutdown

errors:
  critical: Произошла какая-то ошибка. Невозможно обработать запрос
  nothing_to_cancel: ✖️ Нечего отменять
  bad_link: ✖️ Плохая ссылка. Не удается обработать
  config_access: Ошибка доступа к файлу конфигурации
  composer: Ошибка при создании документа
  llm: Ошибка в модуле генерации текста
  audio_model: Ошибка в процессе транскрипции
  too_many_tasks: ⛔ Слишком много задач. Пожалуйста, повторите попытку позже.
  file_not_found: Не удалось найти файл по указанному пути
  unknown_settings: ⛔ Вы выбрали неправильную настройку, пожалуйста, используйте клавиатуру
