chatgpt:
  provider: OpenAIEmbeddings
  available_context: 4096
  model_params:
    embedding_ctx_length: 4096

synthia:
  provider: LlamaCppEmbeddings
  available_context: 4096
  model_params:
    model_path: "/run/media/dvarkless/LinuxData/Large_Language_Models/models/Synthia_13B_instruct/llama.cpp/synthia-13b-v1.2.Q4_K_M.gguf"
    n_ctx: 4096
    f16_kv: True

    n_gpu_layers: 40
    n_batch: 512
