chatgpt:
  name: "gpt3.5-turbo"
  provider: OpenAI
  window_len: 5000
  window_overlap: 400
  instruction_template: ""
  system_template: ""
  response_template: ""
  available_context: 4096
  model_params:
    model_name: "gpt3.5-turbo"
    temperature: 0.5
    max_tokens: 512

synthia:
  name: "Synthia_13B_instruct"
  window_len: 5000
  window_overlap: 400
  instruction_template: "USER:"
  system_template: "SYSTEM:"
  response_template: "ASSISTANT:"
  provider: LlamaCpp
  available_context: 4096
  model_params:
    model_path: "path/to/model.gguf"
    temperature: 0.5
    top_p: 0.95
    repeat_penalty: 1.15
    top_k: 40
    f16_kv: True

    max_tokens: 250

    n_gpu_layers: 41
    n_batch: 256
    n_ctx: 4096

