whisper_local:
  provider: WhisperLocal
  model_params:
    model_name: "large-v2"
    model_dir: "./models/whisper/"
    is_translate: False
    device: "cuda"

whisper_cloud:
  provider: WhisperCloud
  model_params:
    model_name: "whisper-1"
    model_dir: "./models/whisper/"
    is_translate: False
