telegram_token: TELEGRAM_TOKEN
openai_token: OPENAI_TOKEN
blacklist_path: "users/blacklist.txt"
whitelist_path: "users/whitelist.txt"
mongodb_url: "mongodb://127.0.0.1:27017"
mongodb_name: "summary_bot"
settings_collection: "settings"
tokens_collection: "tokens"
telegram_collection: "telegram"
admin_id: 123456789
